<a href="https://colab.research.google.com/github/chamcham001/Cuala-CSST_101-BSCS_3B/blob/main/Cuala_CSST101_Exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **My First R Program**

# **1. Print**

In [ ]:
print ("Hello World")

[1] "Hello World"

# **2. String Variable**

In [ ]:
myString <- "Hellow World"
num <- 10
floatingnum <- 9.5
isBool <- TRUE

class(myString)
class(num)
class(floatingnum)
class(isBool)

[1] "character"

[1] "numeric"

[1] "numeric"

[1] "logical"

# **3. Numeric Operation**

In [ ]:
x <- 5
y <- 3

sum <- x + y
dif <- x - y
mul <- x * y
div <- x / y

print (paste("Sum:", sum))
print (paste("dif:", dif))
print (paste("mul:", mul))
print (paste("div:", div))

cat("---------------------------","\n")

cat("+", sum, "\n")
cat("-", dif, "\n")
cat("*", mul, "\n")
cat("/", div, "\n")

[1] "Sum: 8"
[1] "dif: 2"
[1] "mul: 15"
[1] "div: 1.66666666666667"
---------------------------
+ 8
- 2
* 15
/ 1.666667

# **4. User Input**

In [ ]:
name = readline("Enter Name: ")
print(paste("My name is", name))

Enter Name: Chamer
[1] "My name is Chamer"

# **5. Decision Making**

In [ ]:
grade <- 87

if (grade < 75){
  print ("Failed")
}else
{
  print ("Passed")
}

[1] "Passed"

# **6. Loop**

In [ ]:
for(i in 1:5){
  print(i)
}

[1] 1
[1] 2
[1] 3
[1] 4
[1] 5

# **7. Functions**

In [ ]:
addNumber <- function(a,b){
  return (a+b)
}

addNumber (5, 10)

[1] 15

# **8. Vectors**

In [ ]:
grades <- c(90,88, 96, 83,91)

grades

cat("-------------------------", "\n")

cat("Mean", mean(grades), "\n")
cat("Max", max(grades), "\n")
cat("Min", min(grades), "\n")
cat("Sum", sum(grades), "\n")
cat("Length", length(grades), "\n")

[1] 90 88 96 83 91

-------------------------
Mean 89.6
Max 96
Min 83
Sum 448
Length 5

# **9. Matrices**

In [ ]:
A <- matrix(c(1,2,3,4,5,6),nrow = 2)
A

     [,1] [,2] [,3]
[1,] 1    3    5
[2,] 2    4    6

# **10. List**

In [ ]:
student <- list(
  Name="Chamer",
  Age = 20,
  GPA = 1.25
)

student

$Name
[1] "Chamer"

$Age
[1] 20

$GPA
[1] 1.25

# **11. Data Frames**

In [ ]:
students <- data.frame(
  Name = c("Chamer", "JP", "AGA"),
  Age = c(20, 30, 27),
  GPA = c(1.5, 1.5, 1.75)
)

students

write.csv(students, "student.csv")

  Name   Age GPA
1 Chamer 20  1.50
2 JP     30  1.50
3 AGA    27  1.75

# **12. Reading CSV Files**

In [ ]:
data <- read.csv("student.csv")
head(data)

summary(data)

  X Name   Age GPA
1 1 Chamer 20  1.50
2 2 JP     30  1.50
3 3 AGA    27  1.75

       X              Name        Age             GPA
 Min.   :1.0   Length   :3   Min.   :20.00   Min.   :1.500
 1st Qu.:1.5   N.unique :3   1st Qu.:23.50   1st Qu.:1.500
 Median :2.0   N.blank  :0   Median :27.00   Median :1.500
 Mean   :2.0   Min.nchar:2   Mean   :25.67   Mean   :1.583
 3rd Qu.:2.5   Max.nchar:6   3rd Qu.:28.50   3rd Qu.:1.625
 Max.   :3.0                 Max.   :30.00   Max.   :1.750